version: "3.8"
services:
  backend:
    container_name: backend
    build: ./backend/docker
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./backend
        target: /backend
    command: bash -c "npm run start:dev"
  frontend:
    container_name: frontend
    build: ./frontend/docker
    tty: true
    ports:
      - "8000:3000"
    volumes:
      - type: bind
        source: ./frontend
        target: /frontend
    command: sh -c "cd app && npm start"
  postgres:
    image: postgres:14.2-alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./backend/docker/postgres/init.d:/docker-entrypoint-initdb.d
      - ./backend/docker/postgres/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_DB: postgres
    hostname: postgres
    restart: always
    user: root
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 81:80
    environment:
      PGADMIN_DEFAULT_EMAIL: nestjs@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - ./backend/docker/pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    user: root
